
package com.mycompany.gui;

import java.awt.Event;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class FORMULARIO extends javax.swing.JFrame {

   //ATRIBUTOS
    ArrayList<Estudiantes> vEstudiantes = new ArrayList<>();
    DefaultListModel moEstudiantes;
    DefaultTableModel modeloTabla;
    
    public FORMULARIO() {
        
       
        initComponents();
        setLocationRelativeTo(null);//centrar ventana
        CrearModelo();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genre = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        chkProgramación = new javax.swing.JCheckBox();
        chkCoaching = new javax.swing.JCheckBox();
        chkInglés = new javax.swing.JCheckBox();
        cbCiclos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEstudiantes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(465, 500));
        setPreferredSize(new java.awt.Dimension(485, 500));
        setSize(new java.awt.Dimension(490, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(28, 33, 30, 14);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 77, 50, 14);

        jLabel3.setText("Género");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(28, 128, 70, 14);

        jLabel4.setText("Ciclo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(28, 246, 30, 14);
        getContentPane().add(txtID);
        txtID.setBounds(98, 28, 193, 25);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(98, 71, 193, 25);

        Genre.add(rbMasculino);
        rbMasculino.setText("Masculino");
        getContentPane().add(rbMasculino);
        rbMasculino.setBounds(98, 124, 90, 23);

        Genre.add(rbFemenino);
        rbFemenino.setText("Femenino");
        getContentPane().add(rbFemenino);
        rbFemenino.setBounds(220, 124, 90, 23);

        chkProgramación.setText("Programación");
        chkProgramación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProgramaciónActionPerformed(evt);
            }
        });
        getContentPane().add(chkProgramación);
        chkProgramación.setBounds(28, 184, 100, 23);

        chkCoaching.setText("Coaching");
        chkCoaching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCoachingActionPerformed(evt);
            }
        });
        getContentPane().add(chkCoaching);
        chkCoaching.setBounds(137, 184, 90, 23);

        chkInglés.setText("Inglés");
        chkInglés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkInglésActionPerformed(evt);
            }
        });
        getContentPane().add(chkInglés);
        chkInglés.setBounds(231, 184, 60, 23);

        cbCiclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione un ciclo--", "1. Python", "2. Java", "3. Web( JS, HTML5, CSS3)" }));
        getContentPane().add(cbCiclos);
        cbCiclos.setBounds(104, 241, 187, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(70, 20));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(10, 60, 120, 40);

        btnSalir.setText("Salir");
        btnSalir.setPreferredSize(new java.awt.Dimension(70, 20));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(10, 110, 120, 40);

        btnAgregar1.setText("Agregar");
        btnAgregar1.setPreferredSize(new java.awt.Dimension(70, 20));
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar1);
        btnAgregar1.setBounds(10, 10, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 30, 140, 160);

        listEstudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTADO DE ESTUDIANTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 8))); // NOI18N
        jScrollPane1.setViewportView(listEstudiantes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 200, 140, 70);

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEstudiantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblEstudiantesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblEstudiantes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 310, 420, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void chkProgramaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProgramaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProgramaciónActionPerformed

    private void chkCoachingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCoachingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCoachingActionPerformed

    private void chkInglésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInglésActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkInglésActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
     txtID.setText("");
             txtNombre.setText("");
                Genre.clearSelection();
                    chkCoaching.setSelected(false);
                chkProgramación.setSelected(false);
              chkInglés.setSelected(false);
            cbCiclos.setSelectedIndex(0);
             
             
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      // System.exit(0); // Cierra toda la app
      this.dispose(); //cierra ventana en uso
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
      
        //Instancias
        Estudiantes est = new Estudiantes();  // Agregar
        moEstudiantes= new DefaultListModel();//Contiene todos los datos que se mostrarán en la lista/modelo
        
      String subject="";
      
      est.setIdentificacion(Integer.parseInt(txtID.getText()));
      
      est.setNombre(txtNombre.getText());
      
      est.setGenéro(rbFemenino.isSelected()? "Femenino":"Masculino");
      
      if (chkProgramación.isSelected()){
      subject="Programación ";
      }
      
      if (chkCoaching.isSelected()){
      subject+="Coaching ";
      }
      
      if (chkInglés.isSelected()){
      subject+="Inglés ";
      }
      
      est.setMaterias(subject);
      
      est.setCiclo(cbCiclos.getSelectedItem().toString());
      
      //Agrega los estudiantes al arreglo
      vEstudiantes.add(est);
      
      vEstudiantes.forEach(estu -> {
          //los recorre
          moEstudiantes.addElement("Nombre: "+estu.getNombre()+" ID: "+estu.getIdentificacion()+" Ciclo: "+estu.getCiclo());//guarda y muestra
        });
     
        listEstudiantes.setModel(moEstudiantes);//se le asigna el modelo
        
        modeloTabla.setRowCount(0); //reinicia los datos agregados a la tabla para no repetirlos
        for (Estudiantes e : vEstudiantes) {
            String[] datos={Integer.toString(e.getIdentificacion()), e.getNombre()};
                //recorre el arrays list, almacena datos en vector datos y se pasa a la tabla     
                    modeloTabla.addRow(datos);
        }
      
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void tblEstudiantesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEstudiantesKeyReleased
      if(evt.getKeyCode()== Event.ENTER){//verifica se presionó enter para modificar
          int i = tblEstudiantes.getSelectedRow();//linea seleccionada para editar
          int cod=Integer.parseInt(tblEstudiantes.getValueAt(i,0).toString());//identificación del editado (especifica fila y la columna
          int j=0;
          for (Estudiantes e : vEstudiantes) {
              if (e.getIdentificacion()==cod) {
                  e.setNombre(tblEstudiantes.getValueAt(i,0).toString());
                  vEstudiantes.set(j, e);
              }
              j++;
          }
          
      JOptionPane.showMessageDialog(this, "Presionó enter");
      
      }  // evento liberar x tecla
    }//GEN-LAST:event_tblEstudiantesKeyReleased
        
    //metodo, inastancia modelo y nombra cabeceras
    private void CrearModelo (){
    
        String[] head={"Identificación","Nombre"};
     modeloTabla = new DefaultTableModel(null, head);//datos
     tblEstudiantes.setModel(modeloTabla);//mostrar datos
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMULARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Genre;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCiclos;
    private javax.swing.JCheckBox chkCoaching;
    private javax.swing.JCheckBox chkInglés;
    private javax.swing.JCheckBox chkProgramación;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listEstudiantes;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
